server:
  port: 1116


spring:
  application:
    name: API-GATEWAY
  cloud:
   gateway:
    routes:
      - id: EMPLOYEE-SERVICE
        uri: lb://EMPLOYEE-SERVICE
        predicates:
          - Path=/employee/**

      - id: COMPANY-SERVICE
        uri: lb://COMPANY-SERVICE
        predicates:
          - Path=/company/**

      - id: COMPANY-RATING
        uri: lb://COMPANY-RATING
        predicates:
          - Path=/Rating/**
eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka

#okta:
# oauth2:
#  issuer: https://dev-63597725.okta.com/oauth2/default
#  audience: api://default
#  client-id: 0oaanxpq6x1Krn2L95d7
#  client-secrete: fTLjT1GbGX3JYpNl1m2uHMp2bvxHwQqqz5nUQTwrEqfTESxc0gRFXKmCSQqBXYZ0
#  scopes: openid, profile, email, offline_access






